routes/admin.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\ConfirmPasswordController;


//Auth::routes(['login' => false, 'register' => false]);
// Authentication Routes...
Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('login', [LoginController::class, 'login']);
Route::any('logout', [LoginController::class, 'logout'])->name('logout');

// Registration Routes...
Route::get('register', [RegisterController::class, 'showRegistrationForm'])->name('register');
Route::post('register', [RegisterController::class, 'register']);

// Password Reset Routes...
Route::get('password/reset', [ForgotPasswordController::class, 'showLinkRequestForm'])->name('password.request');
Route::post('password/email', [ForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.email');
Route::get('password/reset/{token}', [ResetPasswordController::class, 'showResetForm'])->name('password.reset');
Route::post('password/reset', [ResetPasswordController::class, 'reset'])->name('password.update');

// Confirm Password Routes...
Route::get('password/confirm', [ConfirmPasswordController::class, 'showConfirmForm'])->name('password.confirm');
Route::post('password/confirm', [ConfirmPasswordController::class, 'confirm']);



Route::get('/', function () { return redirect()->route('login');});
Route::middleware(['auth'])->group( function(){

    Route::get('/home', [HomeController::class, 'index'])->name('home');
    Route::resource('members', MemberController::class)->except(['destroy']);
    Route::get('members/{member}/destroy', [MemberController::class, 'destroy'])->name('members.destroy');
    Route::get('members/{member}/events-attended', [MemberController::class, 'EventsAttended'])->name('members.events.attended');

    Route::resource('event_categories', EventCategoryController::class)->except(['destroy']);
    Route::get('event_categories/{event_category}/destroy', [EventCategoryController::class, 'destroy'])->name('event_categories.destroy');

    Route::resource('events', EventController::class)->except(['destroy']);
    Route::get('events/{event}/destroy', [EventController::class, 'destroy'])->name('events.destroy');
    Route::any('events/add/members-to-event/{event}', [EventController::class, 'AddMembersToEvent'])->name('add.members.to.event');

    Route::resource('departments', DepartmentController::class)->except(['destroy']);
    Route::get('departments/{department}/destroy', [DepartmentController::class, 'destroy'])->name('departments.destroy');

    Route::resource('groups', GroupController::class)->except(['destroy']);
    Route::get('groups/{group}/destroy', [GroupController::class, 'destroy'])->name('groups.destroy');

});

routes/web.php
<?php
namespace App\Http\Controllers;


//use App\Http\Controllers\Auth\ConfirmPasswordController;
//use Illuminate\Support\Facades\Auth;
//use Illuminate\Support\Facades\Route;
//use App\Http\Controllers\HomeController;
//use App\Http\Controllers\MemberController;
//use App\Http\Controllers\Auth\LoginController;
//use App\Http\Controllers\Auth\RegisterController;
//use App\Http\Controllers\Auth\ForgotPasswordController;
//use App\Http\Controllers\Auth\ResetPasswordController;




/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

////Auth::routes(['login' => false, 'register' => false]);
//// Authentication Routes...
//Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
//Route::post('login', [LoginController::class, 'login']);
//Route::any('logout', [LoginController::class, 'logout'])->name('logout');
//
//// Registration Routes...
//Route::get('register', [RegisterController::class, 'showRegistrationForm'])->name('register');
//Route::post('register', [RegisterController::class, 'register']);
//
//// Password Reset Routes...
//Route::get('password/reset', [ForgotPasswordController::class, 'showLinkRequestForm'])->name('password.request');
//Route::post('password/email', [ForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.email');
//Route::get('password/reset/{token}', [ResetPasswordController::class, 'showResetForm'])->name('password.reset');
//Route::post('password/reset', [ResetPasswordController::class, 'reset'])->name('password.update');
//
//// Confirm Password Routes...
//Route::get('password/confirm', [ConfirmPasswordController::class, 'showConfirmForm'])->name('password.confirm');
//Route::post('password/confirm', [ConfirmPasswordController::class, 'confirm']);
//
//
//
//Route::get('/', function () { return redirect()->route('login');});
//Route::middleware(['auth'])->group( function(){
//
//    Route::get('/home', [HomeController::class, 'index'])->name('home');
//    Route::resource('members', MemberController::class)->except(['destroy']);
//    Route::get('members/{member}/destroy', [MemberController::class, 'destroy'])->name('members.destroy');
//    Route::get('members/{member}/events-attended', [MemberController::class, 'EventsAttended'])->name('members.events.attended');
//
//    Route::resource('event_categories', EventCategoryController::class)->except(['destroy']);
//    Route::get('event_categories/{event_category}/destroy', [EventCategoryController::class, 'destroy'])->name('event_categories.destroy');
//
//    Route::resource('events', EventController::class)->except(['destroy']);
//    Route::get('events/{event}/destroy', [EventController::class, 'destroy'])->name('events.destroy');
//    Route::any('events/add/members-to-event/{event}', [EventController::class, 'AddMembersToEvent'])->name('add.members.to.event');
//
//    Route::resource('departments', DepartmentController::class)->except(['destroy']);
//    Route::get('departments/{department}/destroy', [DepartmentController::class, 'destroy'])->name('departments.destroy');
//
//    Route::resource('groups', GroupController::class)->except(['destroy']);
//    Route::get('groups/{group}/destroy', [GroupController::class, 'destroy'])->name('groups.destroy');
//
//});

app/Models/Event.php
<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Event extends Model
{
    use SoftDeletes;
    protected $guarded = ['id'];

    public function members(){
        return $this->belongsToMany(Member::class, 'event_members', 'event_id', 'member_id')->withTimestamps();
    }

    public function category(){
        return $this->belongsTo(EventCategory::class, 'category_id');
    }

    public function creator(){
        return $this->belongsTo(User::class, 'created_by');
    }


}

app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\AddMembersToEventDataTable;
use App\DataTables\EventDataTable;
use App\Models\Event;
use App\Models\Event_Member;
use App\Models\EventCategory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class EventController extends Controller
{

    public function index(EventDataTable $dataTable, Request $request)
    {
        $event_category = EventCategory::query()->find($request->category_id);

        if($event_category){
            return $dataTable->with([
                'category_id' => $request->category_id,
            ])->render('events.index', compact('event_category'));

        }else{
            return redirect()->back()->with('error', 'This Event Category does not exist');
        }

    }


    public function create()
    {
        return view('events.create', [
            'event_category' => EventCategory::all(),
        ]);
    }


    public function store(Request $request)
    {
        $data = $request->validate([
            'event_name' => 'required|string|min:3',
            'event_date_time' => 'required|date_format:Y-m-d\TH:i',
            'venue' => 'required|string|min:3',
            'comment' => 'required|string|min:3',
            'category_id' => 'required|exists:App\Models\EventCategory,id',
        ]);
        $data['created_by'] = auth()->id();
        $category = $request->category_id;

        DB::beginTransaction();
        try {
            Event::query()->create($data);
            DB::commit();
            }catch (\Exception $e){
            DB::rollBack();

            return redirect()->route('events.index',['category_id' =>$category])->with('error', 'Event registration failed');
        }

        return redirect()->route('events.index',['category_id' =>$category])->with('success', 'Event registration was successful');
    }


    public function show(Event $event)
    {
        //
    }


    public function edit(Event $event)
    {
        $event_category = EventCategory::all();
        return view('events.edit', compact('event', 'event_category'));
    }


    public function update(Request $request, Event $event)
    {
//        dd($request->all());

        $data = $request->validate([
            'event_name' => 'required|string|min:3',
            'event_date_time' => 'required|date_format:Y-m-d\TH:i',
            'venue' => 'required|string|min:3',
            'comment' => 'required|string|min:3',
            'category_id' => 'required|exists:App\Models\EventCategory,id',
        ]);
        $data['created_by'] = auth()->id();
        $category = $request->category_id;

        DB::beginTransaction();
        try {
            $event->update($data);
            DB::commit();
        }catch (\Exception $e){
            DB::rollBack();

            return redirect()->route('events.index',['category_id' =>$category])->with('error', 'Event update failed');
        }

        return redirect()->route('events.index',['category_id' =>$category])->with('success', 'Event update was successful');
    }


    public function destroy(Event $event)
    {
        DB::beginTransaction();
        try {
            $event->delete();
            DB::commit();
        } catch (\Exception $e){
            DB::rollBack();
            return redirect()->back()->with('error', 'Event Deletion Failed');

        }

        return back()->with('success', 'Event Deletion was Successful');
    }



    public function AddMembersToEvent(AddMembersToEventDataTable $dataTable, Request $request,Event $event){

        if($request->isMethod("POST")){

            $request->validate([
                'member_id' => 'exists:members,id',
            ]);

//            $event->members()->attach($request->member_id);
            $event->members()->sync($request->member_id);

            $members = $event->members()->pluck('member_id');

            return redirect()->back()->with(['success'=>'Members successfully added to Event',compact('event', 'members')]);
//            return $dataTable->with('success', 'Members successfully added to Event')->render('event_members.create', compact('event', 'members'));

        }

        $members = $event->members()->pluck('member_id');

        return $dataTable->render('event_members.create', compact('event', 'members'));
    }

}

resources/views/events/create.blade.php
@extends('layouts.admin')


@section('content')

<div class="card">
  <div class="card-header">
    Create Event
  </div>
  <div class="card-body">
    <div class="col-lg-10 mx-auto">
      <form method="POST" action="{{route('events.store')}}">
          @csrf
          <div class="row">
            <div class="col-lg">
              <div class="form-group ">
                  <label>Event Name</label>
                  <input type="text" name="event_name" value="{{ old('event_name') }}" class="form-control @error('event_name') is-invalid @enderror" placeholder="">
                  @error('event_name')
                  <span class="text-danger" role="alert">
                         {{ $message }}
                     </span>
                  @enderror
              </div>


              <div class="form-group ">
                  <label>Event Date & Time</label>
                  <input type="datetime-local" name="event_date_time" value="{{ old('event_date_time') }}" class="form-control @error('event_date_time') is-invalid @enderror" placeholder="">
                  @error('event_date_time')
                  <span class="text-danger" role="alert">
                         {{ $message }}
                     </span>
                  @enderror
              </div>

              <div class="form-group ">
                  <label>Venue</label>
                  <input type="text" name="venue" value="{{ old('venue') }}" class="form-control @error('venue') is-invalid @enderror" placeholder="">
                  @error('venue')
                  <span class="text-danger" role="alert">
                         {{ $message }}
                     </span>
                  @enderror
              </div>
            </div>
            <div class="col-lg">
              <div class="form-group ">
                  <label>Comment</label>
                  <input type="text" name="comment" value="{{ old('comment') }}" class="form-control @error('comment') is-invalid @enderror" placeholder="">
                  @error('comment')
                  <span class="text-danger" role="alert">
                         {{ $message }}
                     </span>
                  @enderror
              </div>
              <div class="form-group ">
                  <label>Event Category</label>
                  <select name="category_id" class="selectpicker" title="select category" data-live-search="true" data-live-search-placeholder="Search ...">
                      @foreach($event_category as $category)
                          <option value="{{ $category->id }}" {{ old('category_id') == $category->id  ? 'selected' : '' }}>{{ $category->name }}</option>
                      @endforeach
                  </select>
                  @error('category_id')
                  <span class="text-danger" role="alert">
                     {{ $message }}
                 </span>
                  @enderror
              </div>

              <div>{{ request('category_id') }}</div>
            </div>
          </div>
          <div class="text-center">
            <a href="{{ url()->previous() }}" class="btn btn-sm col-lg-3 btn-danger">Cancel</a>
{{--                        <a href="{{ route('events.index', ['category_id' => request('category_id')]) }}" class="btn btn-sm btn-danger">Cancel</a>--}}
            <button type="submit" class="btn btn-sm col-lg-3 btn-primary">Save & Apply</button>
          </div>
        </form>
    </div>

  </div>
</div>


    {{-- <div class="container">
        <div class="pt-3 pb-4 mb-4 ">
            <div class="row border-bottom">
                <div class="col-lg-6">
                    <h2 class="heading h2 font-weight-bold">Create Event</h2>
                </div>
            </div>

            <form method="POST" action="{{route('events.store')}}">
                @csrf
                <div class="row mt-3 mb-4">
                    <div class="form-group col-md-3">
                        <label>Event Name</label>
                        <input type="text" name="event_name" value="{{ old('event_name') }}" class="form-control @error('event_name') is-invalid @enderror" placeholder="">
                        @error('event_name')
                        <span class="text-danger" role="alert">
                               {{ $message }}
                           </span>
                        @enderror
                    </div>


                    <div class="form-group col-md-3">
                        <label>Event Date & Time</label>
                        <input type="datetime-local" name="event_date_time" value="{{ old('event_date_time') }}" class="form-control @error('event_date_time') is-invalid @enderror" placeholder="">
                        @error('event_date_time')
                        <span class="text-danger" role="alert">
                               {{ $message }}
                           </span>
                        @enderror
                    </div>

                    <div class="form-group col-md-3">
                        <label>Venue</label>
                        <input type="text" name="venue" value="{{ old('venue') }}" class="form-control @error('venue') is-invalid @enderror" placeholder="">
                        @error('venue')
                        <span class="text-danger" role="alert">
                               {{ $message }}
                           </span>
                        @enderror
                    </div>

                    <div class="form-group col-md-3">
                        <label>Comment</label>
                        <input type="text" name="comment" value="{{ old('comment') }}" class="form-control @error('comment') is-invalid @enderror" placeholder="">
                        @error('comment')
                        <span class="text-danger" role="alert">
                               {{ $message }}
                           </span>
                        @enderror
                    </div>
                </div>



                <div class="row mb-3">
                    <div class="form-group col-md-3">
                        <label>Event Category</label>
                        <select name="category_id" class="selectpicker" title="select category" data-live-search="true" data-live-search-placeholder="Search ...">
                            @foreach($event_category as $category)
                                <option value="{{ $category->id }}" {{ old('category_id') == $category->id  ? 'selected' : '' }}>{{ $category->name }}</option>
                            @endforeach
                        </select>
                        @error('category_id')
                        <span class="text-danger" role="alert">
                           {{ $message }}
                       </span>
                        @enderror
                    </div>

                    <div>{{ request('category_id') }}</div>

                    <div class="col-md-3 mt-4 pt-2">
                        <a href="{{ url()->previous() }}" class="btn btn-sm btn-danger">Cancel</a>

                        <button type="submit" class="btn btn-sm btn-primary">Save & Apply</button>
                    </div>

                </div>


                <div class="row mb-4">

                </div>

            </form>

        </div>

    </div> --}}
@endsection

resources/views/events/edit.blade.php
@extends('layouts.admin')


@section('content')

    <div class="card">
        <div class="card-header">
            Create Event
        </div>
        <div class="card-body">
            <div class="col-lg-10 mx-auto">
                <form method="POST" action="{{route('events.update', $event->id)}}">
                    @method('PATCH')
                    @csrf
                    <div class="row">
                        <div class="col-lg">
                            <div class="form-group ">
                                <label>Event Name</label>
                                <input type="text" name="event_name" value="{{ old('event_name') ?? $event->event_name }}" class="form-control @error('event_name') is-invalid @enderror" placeholder="">
                                @error('event_name')
                                <span class="text-danger" role="alert">
                                    {{ $message }}
                                </span>
                                @enderror
                            </div>


                            <div class="form-group ">
                                <label>Event Date & Time</label>
                                <input type="datetime-local" name="event_date_time" value="{{ old('event_date_time') ? \Carbon\Carbon::parse(old('event_date_time'))->format('Y-m-d\TH:i'): \Carbon\Carbon::parse($event->event_date_time)->format('Y-m-d\TH:i') }}" class="form-control @error('event_date_time') is-invalid @enderror" placeholder="">
                                @error('event_date_time')
                                <span class="text-danger" role="alert">
                                    {{ $message }}
                                </span>
                                @enderror
                            </div>

                            <div class="form-group ">
                                <label>Venue</label>
                                <input type="text" name="venue" value="{{ old('venue') ?? $event->venue }}" class="form-control @error('venue') is-invalid @enderror" placeholder="">
                                @error('venue')
                                <span class="text-danger" role="alert">
                                    {{ $message }}
                                </span>
                                @enderror
                            </div>
                        </div>
                        <div class="col-lg">
                            <div class="form-group ">
                                <label>Comment</label>
                                <input type="text" name="comment" value="{{ old('comment') ?? $event->comment }}" class="form-control @error('comment') is-invalid @enderror" placeholder="">
                                @error('comment')
                                <span class="text-danger" role="alert">
                                    {{ $message }}
                                </span>
                                @enderror
                            </div>
                            <div class="form-group ">
                                <label>Event Category</label>
                                <select name="category_id" class="selectpicker" title="select category" data-live-search="true" data-live-search-placeholder="Search ...">
                                    @foreach($event_category as $category)
                                        <option value="{{ $category->id }}" {{ old('category_id') ? (old('category_id') == $category->id  ? 'selected' : '') : ($event->category_id == $category->id  ? 'selected' : '') }}>{{ $category->name }}</option>
                                    @endforeach
                                </select>
                                @error('category_id')
                                <span class="text-danger" role="alert">
                                    {{ $message }}
                                </span>
                                @enderror
                            </div>

                            <div>{{ request('category_id') }}</div>
                        </div>
                    </div>
                    <div class="text-center">
                        <a href="{{ url()->previous() }}" class="btn btn-sm col-lg-3 btn-danger">Cancel</a>
                        {{--                        <a href="{{ route('events.index', ['category_id' => request('category_id')]) }}" class="btn btn-sm btn-danger">Cancel</a>--}}
                        <button type="submit" class="btn btn-sm col-lg-3 btn-primary">Update & Apply</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
@endsection

resources/views/events/index.blade.php
@extends('layouts.admin')

@section('title', 'Event')
@section('admin_css')

    <link rel="stylesheet" href="{!! asset('css/dataTables.bootstrap.min.css') !!}" type="text/css">
    <link rel="stylesheet" href="{!! asset('css/dataTables.bootstrap4.css') !!}" type="text/css">

    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.2/css/buttons.dataTables.min.css"/>

@endsection
@section('content')


    <div class="">

        <div class="card">
            <div class="card-header">
                {{ $event_category->name }}  Event list

                <div class="float-right">
                    <a href="{{ route('event_categories.index') }}" class="btn btn-danger btn-sm"><i class="fa fa-arrow-circle-left"></i> Go Back</a>
                    <a href="{{ route('events.create') }}" class="btn btn-primary btn-sm"><i class="fa fa-plus-circle"></i> Add Event</a>
                </div>
            </div>

            <div class="card-body">
                <div class="table-responsive">
                <div class="row">
                  <div class="mx-auto">
                    @include('includes.alert')
                  </div>
                </div>
                <!--begin: Datatable-->
                {!! $dataTable->table(['class'=> 'table table-striped table-bordered',]) !!}
                <!--end: Datatable-->
                </div>
            </div>
        </div>

    </div>


@endsection

@push('scripts')
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
    <script src="{!! asset('vendor/datatables/buttons.server-side.js') !!}"></script>
    <script src="{!! asset('js/dataTables.buttons.min.js') !!}"></script>
    <script src="{!! asset('js/buttons.server-side.js') !!}"></script>
    {!! $dataTable->scripts() !!}

@endpush