routes/admin.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\ConfirmPasswordController;


//Auth::routes(['login' => false, 'register' => false]);
// Authentication Routes...
Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('login', [LoginController::class, 'login']);
Route::any('logout', [LoginController::class, 'logout'])->name('logout');

// Registration Routes...
Route::get('register', [RegisterController::class, 'showRegistrationForm'])->name('register');
Route::post('register', [RegisterController::class, 'register']);

// Password Reset Routes...
Route::get('password/reset', [ForgotPasswordController::class, 'showLinkRequestForm'])->name('password.request');
Route::post('password/email', [ForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.email');
Route::get('password/reset/{token}', [ResetPasswordController::class, 'showResetForm'])->name('password.reset');
Route::post('password/reset', [ResetPasswordController::class, 'reset'])->name('password.update');

// Confirm Password Routes...
Route::get('password/confirm', [ConfirmPasswordController::class, 'showConfirmForm'])->name('password.confirm');
Route::post('password/confirm', [ConfirmPasswordController::class, 'confirm']);



Route::get('/', function () { return redirect()->route('login');});
Route::middleware(['auth'])->group( function(){

    Route::get('/home', [HomeController::class, 'index'])->name('home');
    Route::resource('members', MemberController::class)->except(['destroy']);
    Route::get('members/{member}/destroy', [MemberController::class, 'destroy'])->name('members.destroy');
    Route::get('members/{member}/events-attended', [MemberController::class, 'EventsAttended'])->name('members.events.attended');

    Route::resource('event_categories', EventCategoryController::class)->except(['destroy']);
    Route::get('event_categories/{event_category}/destroy', [EventCategoryController::class, 'destroy'])->name('event_categories.destroy');

    Route::resource('events', EventController::class)->except(['destroy']);
    Route::get('events/{event}/destroy', [EventController::class, 'destroy'])->name('events.destroy');
    Route::any('events/add/members-to-event/{event}', [EventController::class, 'AddMembersToEvent'])->name('add.members.to.event');

    Route::resource('departments', DepartmentController::class)->except(['destroy']);
    Route::get('departments/{department}/destroy', [DepartmentController::class, 'destroy'])->name('departments.destroy');

    Route::resource('groups', GroupController::class)->except(['destroy']);
    Route::get('groups/{group}/destroy', [GroupController::class, 'destroy'])->name('groups.destroy');

});

routes/web.php
<?php
namespace App\Http\Controllers;


//use App\Http\Controllers\Auth\ConfirmPasswordController;
//use Illuminate\Support\Facades\Auth;
//use Illuminate\Support\Facades\Route;
//use App\Http\Controllers\HomeController;
//use App\Http\Controllers\MemberController;
//use App\Http\Controllers\Auth\LoginController;
//use App\Http\Controllers\Auth\RegisterController;
//use App\Http\Controllers\Auth\ForgotPasswordController;
//use App\Http\Controllers\Auth\ResetPasswordController;




/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

////Auth::routes(['login' => false, 'register' => false]);
//// Authentication Routes...
//Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
//Route::post('login', [LoginController::class, 'login']);
//Route::any('logout', [LoginController::class, 'logout'])->name('logout');
//
//// Registration Routes...
//Route::get('register', [RegisterController::class, 'showRegistrationForm'])->name('register');
//Route::post('register', [RegisterController::class, 'register']);
//
//// Password Reset Routes...
//Route::get('password/reset', [ForgotPasswordController::class, 'showLinkRequestForm'])->name('password.request');
//Route::post('password/email', [ForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.email');
//Route::get('password/reset/{token}', [ResetPasswordController::class, 'showResetForm'])->name('password.reset');
//Route::post('password/reset', [ResetPasswordController::class, 'reset'])->name('password.update');
//
//// Confirm Password Routes...
//Route::get('password/confirm', [ConfirmPasswordController::class, 'showConfirmForm'])->name('password.confirm');
//Route::post('password/confirm', [ConfirmPasswordController::class, 'confirm']);
//
//
//
//Route::get('/', function () { return redirect()->route('login');});
//Route::middleware(['auth'])->group( function(){
//
//    Route::get('/home', [HomeController::class, 'index'])->name('home');
//    Route::resource('members', MemberController::class)->except(['destroy']);
//    Route::get('members/{member}/destroy', [MemberController::class, 'destroy'])->name('members.destroy');
//    Route::get('members/{member}/events-attended', [MemberController::class, 'EventsAttended'])->name('members.events.attended');
//
//    Route::resource('event_categories', EventCategoryController::class)->except(['destroy']);
//    Route::get('event_categories/{event_category}/destroy', [EventCategoryController::class, 'destroy'])->name('event_categories.destroy');
//
//    Route::resource('events', EventController::class)->except(['destroy']);
//    Route::get('events/{event}/destroy', [EventController::class, 'destroy'])->name('events.destroy');
//    Route::any('events/add/members-to-event/{event}', [EventController::class, 'AddMembersToEvent'])->name('add.members.to.event');
//
//    Route::resource('departments', DepartmentController::class)->except(['destroy']);
//    Route::get('departments/{department}/destroy', [DepartmentController::class, 'destroy'])->name('departments.destroy');
//
//    Route::resource('groups', GroupController::class)->except(['destroy']);
//    Route::get('groups/{group}/destroy', [GroupController::class, 'destroy'])->name('groups.destroy');
//
//});

app/Models/EventCategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class EventCategory extends Model
{
    use SoftDeletes;
    protected $guarded = ['id'];

    public function events(){
        $this->hasMany(Event::class, 'category_id');
    }
}

app/Http/Controllers/EventCategoryController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\EventCategoryDataTable;
use App\Models\EventCategory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class EventCategoryController extends Controller
{

    public function index(EventCategoryDataTable $dataTable)
    {
        return $dataTable->render('event_category.index');
    }


    public function create()
    {
        //
    }


    public function store(Request $request)
    {

        DB::beginTransaction();
        try{
            $data = $request->validate([
                'name' => 'required|min:5',
            ]);
            $data['user_id'] = auth()->id();

            EventCategory::query()->create($data);
            DB::commit();
        }catch (\Exception $e){
            DB::rollBack();
            return back()->with('error', 'Addition of Event Category Failed! Name is required and should have at least 5 characters')->withInput();
        }

        return back()->with('success', 'Addition of Event Category was successful');
    }


    public function show(EventCategory $eventCategory)
    {
        //
    }


    public function edit(EventCategory $eventCategory)
    {
        return view('event_category.edit', compact('eventCategory'));
    }


    public function update(Request $request, EventCategory $eventCategory)
    {
        $data = $request->validate([
            'name' => 'required|min:5',
        ]);
        $data['user_id'] = auth()->id();

        DB::beginTransaction();
        try{
            $eventCategory->update($data);
            DB::commit();
        }catch (\Exception $e){
            DB::rollBack();
            return back()->with('error', 'Update of Event Category Failed!');
        }

        return redirect()->route('event_categories.index')->with('success', 'Update of Event Category was successful');

    }


    public function destroy(EventCategory $eventCategory)
    {
        DB::beginTransaction();
        try {
            $eventCategory->delete();
            DB::commit();
        } catch (\Exception $e){
            DB::rollBack();
            return redirect()->back()->with('error', 'Event Category Deletion Failed');

        }

        return back()->with('success', 'Event Category Deletion was Successful');
    }
}

resources/views/event_category/edit.blade.php
@extends('layouts.admin')

@section('title', 'Event Category')
@section('content')

<div class="row">
  <div class="col-lg-5 mx-auto">
    <div class="card">
      <div class="card-header">
        Edit Event Category
      </div>
      <div class="card-body">
        <form method="POST" action="{{route('event_categories.update', $eventCategory->id)}}">
            @method('PATCH')
            @csrf
            <div class="form-group">
                <label>Category Name</label>
                <input type="text" name="name" value="{{ old('name') ?? $eventCategory->name }}" class="form-control @error('name') is-invalid @enderror">
                @error('name')
                <span class="text-danger" role="alert">
                       {{ $message }}
                   </span>
                @enderror
            </div>
            <div class="text-center">
              <a href="{{ route('event_categories.index') }}" class="btn btn-sm btn-danger  text-white mr-2"> <i class="fa fa-sm fa-arrow-left"></i> Cancel</a>

              <button type="submit" class="btn btn-sm btn-primary"> Update </button>
            </div>
          </form>
      </div>
    </div>
  </div>
</div>


@endsection

resources/views/event_category/index.blade.php
@extends('layouts.admin')

@section('title', 'Event Category')
@section('admin_css')

    <link rel="stylesheet" href="{!! asset('css/dataTables.bootstrap.min.css') !!}" type="text/css">
    <link rel="stylesheet" href="{!! asset('css/dataTables.bootstrap4.css') !!}" type="text/css">

    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.2/css/buttons.dataTables.min.css"/>

@endsection
@section('content')


    <div class="">

        <div class="card">
            <div class="card-header">
                Event Category

                <div class="float-right" data-toggle="modal" data-target="#modal_5">
                    <a class="btn btn-tertiary text-white btn-sm"><i class="fa fa-plus-circle"></i> Add Event Category</a>
                </div>
            </div>

            <div class="card-body">
                <div class="table-responsive">
                @include('includes.alert')
                <!--begin: Datatable-->
                {!! $dataTable->table(['class'=> 'table table-striped table-bordered',]) !!}
                <!--end: Datatable-->
                </div>
            </div>
        </div>

    </div>






    <!-- Create Event Category Modal -->
    <div class="modal fade position-fixed" id="modal_5" tabindex="-1" role="dialog" aria-labelledby="modal_5" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modal_title_6">Add Event Category</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form method="POST" action="{{ route('event_categories.store') }}">
                    @csrf
                <div class="modal-body">
                    <div class="row col-md-12">

                            <div class="form-group col-md-12">
                                <label>Category Name</label>
                                <input type="text" name="name" value="{{ old('name') }}" class="form-control @error('name') is-invalid @enderror" required placeholder="">
                                @error('name')
                                <span class="text-danger" role="alert">
                               {{ $message }}
                           </span>
                                @enderror
                            </div>


                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-sm btn-primary">Save & Apply</button>
                    <button type="button" class="btn btn-sm btn-danger" data-dismiss="modal">Cancel</button>
                </div>
            </form>
            </div>
        </div>
    </div>



@endsection

@push('scripts')
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
    <script src="{!! asset('vendor/datatables/buttons.server-side.js') !!}"></script>
    <script src="{!! asset('js/dataTables.buttons.min.js') !!}"></script>
    <script src="{!! asset('js/buttons.server-side.js') !!}"></script>
    {!! $dataTable->scripts() !!}

@endpush