routes/admin.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\ConfirmPasswordController;


//Auth::routes(['login' => false, 'register' => false]);
// Authentication Routes...
Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('login', [LoginController::class, 'login']);
Route::any('logout', [LoginController::class, 'logout'])->name('logout');

// Registration Routes...
Route::get('register', [RegisterController::class, 'showRegistrationForm'])->name('register');
Route::post('register', [RegisterController::class, 'register']);

// Password Reset Routes...
Route::get('password/reset', [ForgotPasswordController::class, 'showLinkRequestForm'])->name('password.request');
Route::post('password/email', [ForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.email');
Route::get('password/reset/{token}', [ResetPasswordController::class, 'showResetForm'])->name('password.reset');
Route::post('password/reset', [ResetPasswordController::class, 'reset'])->name('password.update');

// Confirm Password Routes...
Route::get('password/confirm', [ConfirmPasswordController::class, 'showConfirmForm'])->name('password.confirm');
Route::post('password/confirm', [ConfirmPasswordController::class, 'confirm']);



Route::get('/', function () { return redirect()->route('login');});
Route::middleware(['auth'])->group( function(){

    Route::get('/home', [HomeController::class, 'index'])->name('home');
    Route::resource('members', MemberController::class)->except(['destroy']);
    Route::get('members/{member}/destroy', [MemberController::class, 'destroy'])->name('members.destroy');
    Route::get('members/{member}/events-attended', [MemberController::class, 'EventsAttended'])->name('members.events.attended');

    Route::resource('event_categories', EventCategoryController::class)->except(['destroy']);
    Route::get('event_categories/{event_category}/destroy', [EventCategoryController::class, 'destroy'])->name('event_categories.destroy');

    Route::resource('events', EventController::class)->except(['destroy']);
    Route::get('events/{event}/destroy', [EventController::class, 'destroy'])->name('events.destroy');
    Route::any('events/add/members-to-event/{event}', [EventController::class, 'AddMembersToEvent'])->name('add.members.to.event');

    Route::resource('departments', DepartmentController::class)->except(['destroy']);
    Route::get('departments/{department}/destroy', [DepartmentController::class, 'destroy'])->name('departments.destroy');

    Route::resource('groups', GroupController::class)->except(['destroy']);
    Route::get('groups/{group}/destroy', [GroupController::class, 'destroy'])->name('groups.destroy');

});

routes/web.php
<?php
namespace App\Http\Controllers;


//use App\Http\Controllers\Auth\ConfirmPasswordController;
//use Illuminate\Support\Facades\Auth;
//use Illuminate\Support\Facades\Route;
//use App\Http\Controllers\HomeController;
//use App\Http\Controllers\MemberController;
//use App\Http\Controllers\Auth\LoginController;
//use App\Http\Controllers\Auth\RegisterController;
//use App\Http\Controllers\Auth\ForgotPasswordController;
//use App\Http\Controllers\Auth\ResetPasswordController;




/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

////Auth::routes(['login' => false, 'register' => false]);
//// Authentication Routes...
//Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
//Route::post('login', [LoginController::class, 'login']);
//Route::any('logout', [LoginController::class, 'logout'])->name('logout');
//
//// Registration Routes...
//Route::get('register', [RegisterController::class, 'showRegistrationForm'])->name('register');
//Route::post('register', [RegisterController::class, 'register']);
//
//// Password Reset Routes...
//Route::get('password/reset', [ForgotPasswordController::class, 'showLinkRequestForm'])->name('password.request');
//Route::post('password/email', [ForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.email');
//Route::get('password/reset/{token}', [ResetPasswordController::class, 'showResetForm'])->name('password.reset');
//Route::post('password/reset', [ResetPasswordController::class, 'reset'])->name('password.update');
//
//// Confirm Password Routes...
//Route::get('password/confirm', [ConfirmPasswordController::class, 'showConfirmForm'])->name('password.confirm');
//Route::post('password/confirm', [ConfirmPasswordController::class, 'confirm']);
//
//
//
//Route::get('/', function () { return redirect()->route('login');});
//Route::middleware(['auth'])->group( function(){
//
//    Route::get('/home', [HomeController::class, 'index'])->name('home');
//    Route::resource('members', MemberController::class)->except(['destroy']);
//    Route::get('members/{member}/destroy', [MemberController::class, 'destroy'])->name('members.destroy');
//    Route::get('members/{member}/events-attended', [MemberController::class, 'EventsAttended'])->name('members.events.attended');
//
//    Route::resource('event_categories', EventCategoryController::class)->except(['destroy']);
//    Route::get('event_categories/{event_category}/destroy', [EventCategoryController::class, 'destroy'])->name('event_categories.destroy');
//
//    Route::resource('events', EventController::class)->except(['destroy']);
//    Route::get('events/{event}/destroy', [EventController::class, 'destroy'])->name('events.destroy');
//    Route::any('events/add/members-to-event/{event}', [EventController::class, 'AddMembersToEvent'])->name('add.members.to.event');
//
//    Route::resource('departments', DepartmentController::class)->except(['destroy']);
//    Route::get('departments/{department}/destroy', [DepartmentController::class, 'destroy'])->name('departments.destroy');
//
//    Route::resource('groups', GroupController::class)->except(['destroy']);
//    Route::get('groups/{group}/destroy', [GroupController::class, 'destroy'])->name('groups.destroy');
//
//});

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Probably the most complete UI kit out there. Multiple functionalities and controls added,  extended color palette and beautiful typography, designed as its own extended version of Bootstrap at  the highest level of quality.">
    <meta name="author" content="Webpixels">
    <title>ChristCare | @yield('title', 'CIM')</title>
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:400,600,700,800|Roboto:400,500,700" rel="stylesheet">
    <!-- Plugins -->
    <link rel="stylesheet" href="{!! asset('public/vendor/animate/animate.min.css') !!}" type="text/css">
    <link type="text/css" href="{!! asset('public/css/theme.css') !!}" rel="stylesheet">
    <link rel="stylesheet" href="{!! asset('public/vendor/jquery-scrollbar/css/jquery-scrollbar.css') !!}">
    <link type="text/css" href="{!! asset('public/vendor/highlight/css/highlight.min.css') !!}" rel="stylesheet">
    <link type="text/css" href="{!! asset('public/css/demo.css') !!}" rel="stylesheet">
    @yield('admin_css')
</head>
<body>
<main class="main">
    <aside class="sidebar" id="nav_docs">
      <div class="sidebar-brand text-center " style="background-color:white">
              <img src="{{ asset('public/images/care.jpeg') }}" class=" text-center" width="60" height="60">
              <h1 class="font-weight-400"><a href="{{ route('home') }}"><span class="font-weight-700">ChristCare</span> Int. Min</a></h1>
            </div>
<br> <br>
        <div class="scrollbar-inner">
            <ul class="navigation pr-3">
                {{--   MEMBERSHIP   --}}

                <li class="navigation-title">MEMBERSHIP</li>
                <li class="navigation-item">
                    <a href="{{ route('home') }}" class="navigation-link">Dashboard</a>
                    <a href="{{ route('members.index') }}" class="navigation-link">Members</a>
                </li>

                {{--   EVENT MANAGER   --}}
                <li class="navigation-title">EVENT MANAGER</li>
                <li class="navigation-item">
                    <a href="{{ route('event_categories.index') }}" class="navigation-link">Event Category</a>
                </li>

                {{--   SETUP MANAGER   --}}
                <li class="navigation-title">SETUP MANAGER</li>
                <li class="navigation-item">
                    <a href="{{ route('groups.index') }}" class="navigation-link">Groups</a>
                </li>
                <li class="navigation-item">
                    <a href="{{ route('departments.index') }}" class="navigation-link">Departments</a>
                </li>


            </ul>
        </div>
    </aside>

    <section class="content">

        {{--   SIDEBAR IN MOBILE VIEW   --}}
        <div class="header sticky-top">
            <div class="navigation-trigger " data-action="aside-open" data-target=".sidebar">
                <div class="navigation-trigger-inner">
                    <i class="navigation-trigger-line"></i>
                    <i class="navigation-trigger-line"></i>
                    <i class="navigation-trigger-line"></i>
                </div>
            </div>
            <div class="header-brand d-xl-none">
                <h1><a href="index.html">ChristCare Int. Min</a></h1>
            </div>

            {{--   NAVBAR   --}}
            <div class="header-nav ml-auto">
                <ul class="nav align-items-center">
                    {{-- <li class="nav-item d-none d-md-inline-block">
                        <a class="nav-link pl-0 active" href="../">Go to UI Kit</a>
                    </li> --}}
                    {{-- <li class="nav-item d-none d-md-inline-block">
                        <a class="nav-link" href="../docs/changelog.html">Changelog</a>
                    </li> --}}
                    {{-- <li class="nav-item ml-4">
                        <a href="https://github.com/webpixels/boomerang-ui-kit/archive/master.zip" class="btn btn-sm btn-primary">Download Free</a>
                    </li> --}}

                    <li class="nav-item ml-4">
                        <a href="{{ route('logout') }}" onclick="return confirm('Do you want to logout ?')" class="btn btn-sm btn-primary">logout</a>
                    </li>

                </ul>
            </div>
        </div>


        {{--   MAIN CONTENT   --}}
        <div class="content-inner content-docs mb-5">

            @yield('content')

        </div>

        <div class="card-footer mt-5" style=" position: fixed; left: 0; bottom: 0; width: 100%; text-align: center;">
{{--            <p class="p-0 m-0 xs-font-size13 text-center" >© Powered by <a href="https://npontu.com" class="text-dark"> CIM Technologies--}}
{{--                </a></p>--}}
            <div class="">&copy; 2021 <a href="https://webpixels.io/" target="_blank">ChristCare</a>. All rights reserved.</div>

        </div>

        {{--   FOOTER   --}}
{{--        <footer class="footer bg-white fixed-bottom mt-sm-5">--}}
{{--            <div class="container">--}}
{{--                <div class="row align-items-center py-3 py-sm-1 border-top">--}}
{{--                    <div class="col-md-6 text-center text-lg-left mb-2 mb-lg-0">--}}
{{--                        &copy; 2021 <a href="https://webpixels.io/" target="_blank">ChristCare</a>. All rights reserved.--}}
{{--                    </div>--}}
{{--                    <div class="col-lg-6 text-center text-lg-right">--}}
{{--                        <ul class="nav justify-content-center justify-content-lg-end">--}}
{{--                            <li class="nav-item">--}}
{{--                                <a class="nav-link active" href="https://instagram.com/webpixelsofficial" target="_blank"><i class="fab fa-instagram"></i></a>--}}
{{--                            </li>--}}
{{--                            <li class="nav-item">--}}
{{--                                <a class="nav-link" href="https://facebook.com/webpixels" target="_blank"><i class="fab fa-facebook"></i></a>--}}
{{--                            </li>--}}
{{--                            <li class="nav-item">--}}
{{--                                <a class="nav-link" href="https://github.com/webpixels" target="_blank"><i class="fab fa-github"></i></a>--}}
{{--                            </li>--}}
{{--                            <li class="nav-item">--}}
{{--                                <a class="nav-link" href="https://dribbble.com/webpixels" target="_blank"><i class="fab fa-dribbble"></i></a>--}}
{{--                            </li>--}}
{{--                        </ul>--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--            </div>--}}
{{--        </footer>--}}
    </section>
</main>
<!-- Core Script-->
<script src="{!! asset('public/vendor/jquery/jquery.min.js') !!}"></script>
<script src="{!! asset('public/vendor/popper/popper.min.js') !!}"></script>
<script src="{!! asset('public/js/bootstrap/bootstrap.min.js') !!}"></script>
<!-- FontAwesome 5 -->
<script src="{!! asset('public/vendor/fontawesome/js/fontawesome-all.min.js') !!}" defer></script>
<script src="{!! asset('public/vendor/jquery-scrollbar/js/jquery-scrollbar.min.js') !!}"></script>
<script src="{!! asset('public/vendor/jquery-scrollLock/jquery-scrollLock.min.js') !!}"></script>
<script src="{!! asset('public/vendor/sticky-kit/sticky-kit.min.js') !!}"></script>
<script src="{!! asset('public/vendor/highlight/js/highlight.min.js') !!}"></script>
<script src="{!! asset('public/vendor/clipboard-js/clipboard.min.js') !!}"></script>
<script src="{!! asset('public/vendor/holderjs/holder.min.js') !!}"></script>
<script src="{!! asset('public/vendor/bootstrap-select/js/bootstrap-select.min.js') !!}"></script>
<script src="{!! asset('public/js/demo.js') !!}"></script>
<script src="{!! asset('public/js/theme.js') !!}"></script>
@stack('scripts')
@yield('admin_js')
</body>
</html>

resources/views/layouts/admin1.blade.php
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>CIM||Admin</title>
      <!-- Fonts -->
      <link href="https://fonts.googleapis.com/css?family=Nunito:400,600,700,800|Roboto:400,500,700" rel="stylesheet">
    <link rel="stylesheet" href="{!! asset('public/css/demo.css') !!}">
    <link rel="stylesheet" href="{!! asset('public/css/theme.css') !!}">
      <link rel="stylesheet" href="{!! asset('public/vendor/jquery-scrollbar/css/jquery-scrollbar.css') !!}">
      <link type="text/css" href="{!! asset('public/vendor/highlight/css/highlight.min.css') !!}" rel="stylesheet">
    @yield('page-css')
  </head>
  <body data-spy="scroll" data-target="#listexample" data-offset="0">
    <main class="main">
      <aside class="sidebar" id="nav_docs">
            <div class="sidebar-brand text-center " style="background-color:white">
{{--              <img src="{{ asset('public/images/mtnlogo.svg') }}" class=" text-center" width="60" height="60">--}}
              <h1 class="font-weight-400"><a href="../"><span class="font-weight-700">CIM</span></a></h1>
            </div>
            <div class="scrollbar-inner mt-2">
              <ul class="navigation pr-3">
                  <li class="navigation-title">Getting started</li>
                  <li class="navigation-item">
                      <a href="introduction.html" class="navigation-link">Introduction</a>
                  </li>
                  <li class="navigation-item">
                      <a href="file-structure.html" class="navigation-link">File structure</a>
                  </li>
                  <li class="navigation-item">
                      <a href="plugins.html" class="navigation-link">Plugins</a>
                  </li>
                  <li class="navigation-item">
                      <a href="customization.html" class="navigation-link">Customization</a>
                  </li>
                  <li class="navigation-item">
                      <a href="update.html" class="navigation-link">Update</a>
                  </li>
                  <li class="navigation-title">Design elements</li>
                  <li class="navigation-item">
                      <a href="colors.html" class="navigation-link">Colors</a>
                  </li>
                  <li class="navigation-item">
                      <a href="typography.html" class="navigation-link">Typography</a>
                  </li>
                  <li class="navigation-item">
                      <a href="icons.html" class="navigation-link">Icons</a>
                  </li>
                  <li class="navigation-title">Components</li>
                  <li class="navigation-item">
                      <a href="alerts.html" class="navigation-link">Alerts</a>
                  </li>
                  <li class="navigation-item">
                      <a href="avatars.html" class="navigation-link">Avatars</a>
                  </li>
                  <li class="navigation-item">
                      <a href="badges.html" class="navigation-link">Badges</a>
                  </li>
                  <li class="navigation-item">
                      <a href="buttons.html" class="navigation-link">Buttons</a>
                  </li>
                  <li class="navigation-item">
                      <a href="cards.html" class="navigation-link">Cards</a>
                  </li>
                  <li class="navigation-item">
                      <a href="dropdowns.html" class="navigation-link">Dropdowns</a>
                  </li>
                  <li class="navigation-item">
                      <a href="forms.html" class="navigation-link">Forms</a>
                  </li>
                  <li class="navigation-item">
                      <a href="modal.html" class="navigation-link">Modal</a>
                  </li>
                  <li class="navigation-item">
                      <a href="navbar.html" class="navigation-link">Navbar</a>
                  </li>
                  <li class="navigation-item">
                      <a href="navs.html" class="navigation-link">Navs</a>
                  </li>
                  <li class="navigation-item">
                      <a href="pagination.html" class="navigation-link">Pagination</a>
                  </li>
                  <li class="navigation-item">
                      <a href="progress.html" class="navigation-link">Progress</a>
                  </li>
                  <li class="navigation-item">
                      <a href="tables.html" class="navigation-link">Tables</a>
                  </li>
                  <li class="navigation-item">
                      <a href="tooltips.html" class="navigation-link">Tooltips</a>
                  </li>
              </ul>
            </div>
          </aside>
        <div class="header">
            <div class="navigation-trigger d-xl-none" data-action="aside-open" data-target=".sidebar">
              <div class="navigation-trigger-inner">
                <i class="navigation-trigger-line"></i>
                <i class="navigation-trigger-line"></i>
                <i class="navigation-trigger-line"></i>
              </div>
            </div>
            <div class="header-brand d-xl-none">
              <h1><a href="#">CIM</a></h1>
            </div>
            <div class="header-nav ml-auto">
              <ul class="nav align-items-center">

                <li class="nav-item ml-4">
                  <a href="#" class="btn btn-sm text-white" style="background-color:#ffcb05;">Logout</a>
                </li>
              </ul>
            </div>
          </div>

        @yield('page-content')
          <div class="card-footer mt-5" style=" position: fixed; left: 0; bottom: 0; width: 100%; text-align: center;">
            <p class="p-0 m-0 xs-font-size13 text-center" >© Powered by <a href="https://npontu.com" class="text-dark"> CIM Technologies
{{--          <img src="{!! asset('public/images/npontu.jpeg') !!}" class="img-fluid" alt="Npontu Logo" width="50">--}}
                </a></p>
          </div>
</section>
    </main>


    <script src="{!! asset('public/vendor/jquery/jquery.min.js') !!}" ></script>
    <script src="{!! asset('public/vendor/popper/popper.min.js') !!}" ></script>
    <script src="{!! asset('public/js/bootstrap/bootstrap.min.js') !!}" ></script>
    <script src="{!! asset('public/js/theme.js') !!}" ></script>
    <script src="{!! asset('public/js/demo.js') !!}" ></script>
    <script src="{!! asset('public/vendor/fontawesome/js/fontawesome-all.min.js') !!}" ></script>

    <script src="{!! asset('public/vendor/jquery-scrollbar/js/jquery-scrollbar.min.js') !!}" ></script>
    <script src="{!! asset('public/vendor/jquery-scrollLock/jquery-scrollLock.min.js') !!}" ></script>
    <script src="{!! asset('public/vendor/sticky-kit/sticky-kit.min.js') !!}" ></script>
    <script src="{!! asset('public/vendor/highlight/js/highlight.min.js') !!}" ></script>
    <script src="{!! asset('public/vendor/clipboard-js/clipboard.min.js') !!}" ></script>
    <script src="{!! asset('public/vendor/holderjs/holder.min.js') !!}" ></script>

    @yield('page-js')
  </body>
</html>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('public/js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('public/css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/login.blade.php
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ChristCare | Login</title>
    <link rel="stylesheet" href="{{ asset('public/css/demo.css') }}">
    <link rel="stylesheet" href="{{ asset('public/css/theme.css') }}">
    <meta name="google-site-verification" content="K8N68i2PJDrCUqrFDWycHgQhEHW_8XS7kHCJ5XzDzZY" />
    @yield('page-css')
    <link rel="shortcut icon" href="/images/mtnlogo.svg">

  </head>
  <body data-spy="scroll" data-target="#listexample" data-offset="0">

@yield('page-content')


    <script src="{{ asset('public/vendor/jquery/jquery.min.js') }}" ></script>
    <script src="{{ asset('public/vendor/popper/popper.min.js') }}" ></script>
    <script src="{{ asset('public/js/bootstrap/bootstrap.min.js') }}" ></script>
    <script src="{{ asset('public/js/theme.js') }}" ></script>
    <script src="{{ asset('public/vendor/fontawesome/js/fontawesome-all.min.js') }}" defer></script>

    @yield('page-js')
  </body>
</html>